[package]
name = "comm_service"
version = "0.1.3"
authors = ["Chen Weiguang <chen.weiguang@gmail.com>"]

[dependencies]
derive-new = "0.4.0"
error-chain = "0.10.0"
futures = "0.1.13"
futures-cpupool = "0.1.5"
hyper = { version = "0.10.10", default-features = false }
log = "0.3.7"
log4rs = "0.7.0"
regex = "0.2.2"
rouille = "1.0.1"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"
structopt = "0.0.3"
structopt-derive = "0.0.3"
tokio-timer = "0.1.1"
url = "1.4.0"
